import { CaptionStyle } from '@captionstudio/types';

export const CAPTION_STYLE_PRESETS: Record<string, CaptionStyle> = {
  beastYellow: {
    fontFamily: 'Montserrat',
    fontSize: 38,
    fontWeight: '900',
    color: '#FFFFFF',
    textTransform: 'uppercase',
    textAlign: 'center',
    strokeColor: '#000000',
    strokeWidth: 4,
    shadowColor: 'rgba(0,0,0,0.85)',
    shadowBlur: 8,
    positionPreset: 'middle',
    activeWordColor: '#FACC15',
    activeWordScale: 1.18,
  },
  hormoziEmerald: {
    fontFamily: 'Plus Jakarta Sans',
    fontSize: 32,
    fontWeight: '800',
    color: '#F1F5F9',
    strokeColor: '#09090B',
    strokeWidth: 3,
    textTransform: 'uppercase',
    textAlign: 'center',
    positionPreset: 'middle',
    activeWordColor: '#10B981',
    activeWordBgColor: 'rgba(16, 185, 129, 0.2)',
    activeWordScale: 1.15,
  },
  nordicClean: {
    fontFamily: 'Inter',
    fontSize: 22,
    fontWeight: '500',
    color: '#FFFFFF',
    backgroundColor: 'rgba(17, 24, 39, 0.8)',
    backgroundPadding: 10,
    backgroundCornerRadius: 6,
    textAlign: 'center',
    positionPreset: 'bottom',
    activeWordColor: '#FFFFFF',
  },
  cannesCinemaGold: {
    fontFamily: 'Playfair Display',
    fontSize: 26,
    fontWeight: '600',
    color: '#FEF08A',
    shadowColor: '#000000',
    shadowBlur: 6,
    textAlign: 'center',
    positionPreset: 'bottom',
  },
  neonViolet: {
    fontFamily: 'Geist Mono',
    fontSize: 30,
    fontWeight: '800',
    color: '#FFFFFF',
    textTransform: 'uppercase',
    textAlign: 'center',
    strokeColor: '#7C3AED',
    strokeWidth: 3,
    shadowColor: '#8B5CF6',
    shadowBlur: 14,
    positionPreset: 'middle',
    activeWordColor: '#C4B5FD',
    activeWordScale: 1.12,
  },
};

